### ISSUE TITLE
Host parameter with several subdomains won't work

### ISSUE THREAD

**Issue by UniverseXXX** [joshuaavalon/docker-cloudflare#4]
Hi,
I have the following configuration:
```
  DDNS:
    container_name:   "DDNS-Cloudflare"
    image:            "joshuaavalon/cloudflare-ddns"
    restart:          always
    network_mode:     "bridge"
    environment:
      - ZONE=test.com
      - HOST=test.com,sub.test.com,sub2.test.com
      - EMAIL=my@email.com
      - API=HFJLUYLUHG8768JHGJXXXXXXXXX
      - TTL=1
      - PROXY=true
```
however it's not working for some reasons. I've got the error:
`Error: Invalid filter value length specified. Max length is 200`
Please advise if something needs to be changed.
Thanks
Update: it's working if I define only 1 domain in HOST.

**Comment by ElecProg** [comment]
For reference issue #1, it was closed as it didn't really solve any problems (for most people CNAME records work just fine).

However for me they unfortunately don't, quoting my comment on said issue:

"Sometimes (especially if your ISP tends to change your IP every other day) a CNAME record isn't ideal, not entirely sure why but caching seems to be more aggressive and CNAMEs end up not working for me most of the time.

The container doesn't use that much resources (140 KiB) so running once instance per subdomain isn't a real issue however supporting multiple subdomains would make my setup a lot cleaner.

Thanks for this image it works flawlessly!"

**Comment by joshuaavalon** [comment]
@UniverseXXX As @ElecProg said, it is designed to work with one domain. If you want to update several domain, you can

* Use CNAME instead of A record
* Use multiple container
* Write your solution

To have a minimum size container, the scripting is done through bash script. Splitting string and nested if will make the script become very complex and hard to maintain. This need use a proper programming language to build, e.g. Python.

Also, CNAME  should solve most of the issue.

@ElecProg May be you should change the TTL of the CNAME?

**Comment by ElecProg** [comment]
"Write your solution"
Maybe of relevance: <https://stackoverflow.com/questions/27702452/loop-through-a-comma-separated-shell-variable>

@joshuaavalon The TTL could indeed be the culprit, thanks for the suggestion.
